doctrine:
    dbal:
        dbname:    '%env(DB_NAME)%'
        host:      '%env(DB_HOST)%'
        port:      '%env(DB_PORT)%'
        user:      '%env(DB_USER)%'
        password:  '%env(DB_PASS)%'
        driver:    '%env(DB_DRIVER)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/User/Entity'
                prefix: 'App\Module\User\Entity'
                alias: User
            Balance:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/Balance/Entity'
                prefix: 'App\Module\Balance\Entity'
                alias: Balance
            Transaction:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/Transaction/Entity'
                prefix: 'App\Module\Transaction\Entity'
                alias: Transaction
            Service:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Module/Service/Entity'
                prefix: 'App\Module\Service\Entity'
                alias: Service
